# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- feature/*
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
 # UI Layer
- task: Npm@1
    displayName: 'install Angualar Dependencies'
  inputs:
    command: install 
    workingDir: 'ClientApp'
    verbose: false
- task: Npm@1
    displayName: 'Build Angular'
  inputs:
     command: install 
     workingDir: 'ClientApp'
     verbose: false
     customCommand: 'run Build -- Prod'
- task: Npm@1
     displayName: 'Test UI'
  inputs:
     command: install 
     workingDir: 'ClientApp'
     verbose: false
     customCommand: 'run test-- Watch-false'

# Middle Layer
- task: DotNetCoreCLI@2
     displayName: 'Restore Project Dependencies'
  inputs:
     command: 'restore' 
   projects: '**/*.csproj'
- task: DotNetCoreCLI@2
     displayName: 'dotnet build $(buildConfiguration)'
  inputs:
     command: 'build' 
     arguments: '-o restore ..configuration $(buildconfiguration)'
     projects: '**/*.csproj'




    