trigger:
- feature1

pool:
  name: 'Demo'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

variables:
  buildConfiguration: 'Release'
 
stages:
  stage: 
    steps:
      -script: dotnet build --configuration $(buildConfiguration)
       displayName:'dotnet build $(buildConfiguration)'
      -script: dotnet test
       displayName:'dotnet test'
  