# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- develop
- feature/*
pool:
  vmImage: ubuntu-latest
variables:
  buildConfiguration: 'Release'
  dotnetFramework: 'net6.0'
  repository : 'dotnetdemo'
  namespace : 'narmadakubenamespace'
  k8sconnection: 'AzureKubernetes'
  imagePullSecret: 'test'
  containerRegistry: 'narmadacontainerregistry.azurecr.io'
  
stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs:
  - job: 'BuildClient'
    displayName: 'Build job'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'AzureDocker'
          repository: 'dotnetdemo'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: 
            latest        
            $(Build.BuildNumber)
      - task: PublishPipelineArtifact@1
        inputs:
         artifactName: 'manifests'
         path: 'manifests'
        condition: 
- stage: Deploy
  displayName: 'Deployment of Dev'
 
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Manifests
            inputs:
              artifactName: 'manifests'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              namespace: $(namespace)
              dockerRegistryEndpoint: $(AzureDocker)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            
            inputs:
              kubernetesServiceConnection: $(k8sconnection)
              action: deploy
              namespace: $(namespace)
              manifests: |
                $(System.ArtifactsDirectory)/manifests/deployment.yaml
                $(System.ArtifactsDirectory)/manifests/Service.yaml
                $(System.ArtifactsDirectory)/manifests/Ingress.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(Build.BuildNumber)


