version: "3.3"
services:
  web:    
    container_name: web
    build:      
      context: ..
      dockerfile: ./HelloDockerWeb/Dockerfile
    depends_on: [ mssql ]        
    ports:
      - "8080:80"